name: Despliegue de MisiÃ³n NavideÃ±a 2025

on:
  push:
      branches: [ master, main ]
    pull_request:
      branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando CÃ³digo
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalando Dependencias
        run: npm install

      - name: ðŸ”Ž Verificar Formato (Prettier)
        run: npm run format

      - name: ðŸš¨ Ejecutar Linter (ESLint)
        run: npm run lint

      - name: Ejecutando Tests de Seguridad
        run: npm run test:scientific # AquÃ­ es donde muere el deploy si fallan los decimales

      - name: Subiendo a Sentry
        run: |
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          export SENTRY_ORG=${{ secrets.SENTRY_ORG }}
          export SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
          npx @sentry/wizard@latest -i sourcemaps 

      - name: Desplegar en Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'

